### ISSUE TITLE
Support EBS CSI driver and fix ingress

### ISSUE THREAD

**Issue by namcxn** [riskfocus/helm-charts-public#11]
I used this chart install flink but got error

> Error: render error in "flink/templates/ingress.yaml": template: flink/templates/ingress.yaml:26:15: executing "flink/templates/ingress.yaml" at <.host>: can't evaluate field host in type interface {}

and i use eks with EBS CSI driver, chart do not support. And several warnings

> 2020/05/28 15:51:38 Warning: Merging destination map for chart 'flink'. Cannot overwrite table item 'tolerations', with non table value: map[]

> 2020/05/28 15:51:38 Warning: Merging destination map for chart 'flink'. Cannot overwrite table item 'tolerations', with non table value: map[]

I submit PR #10

**Comment by vkropotko** [comment]
Hello @cxnam!
Thank you for your contribution.
Could you please update your PR according to my comments?

**Comment by s-vkropotko** [comment]
#29
