### ISSUE TITLE
Missing capital letter in "zookeeperRootpath" value

### ISSUE THREAD

**Issue by michalgolab** [riskfocus/helm-charts-public#12]
Hi, I've found that during the start of containers there is an error regarding parameter `high-availability.zookeeper.path.root`.

```
kubectl logs pod/flink-taskmanager-0

<snip>
TM_RESOURCES_JVM_PARAMS extraction logs:
<snip>
 - Error while trying to split key and value in configuration file /opt/flink/conf/flink-conf.yaml:13: "    high-availability.zookeeper.path.root: "
<snip>
```

The issue is caused by the following line in `_flink_config.tpl`:

```
high-availability.zookeeper.path.root: {{ .Values.jobmanager.highAvailability.zookeeperRootpath }}
```

As you can see there should be capital letter in `zookeeperRootpath` (in the `values.yaml` it is spelled correctly).

I've prepared fix for this issue here: https://github.com/riskfocus/helm-charts-public/pull/13

**Comment by vkropotko** [comment]
Hello @michalgolab!
Thank for your contribution.
Merged.
