### ISSUE TITLE
Open source license

### ISSUE THREAD

**Issue by prm-dan** [riskfocus/helm-charts-public#17]
Hi!  I was curious if you'd be willing to add an open source license to this Helm chart.  It looks very useful.  No worries if not.

**Comment by gpolek** [comment]
I have the same question, as I would like to use these charts but without license it's not possible for us.

https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository#choosing-the-right-license

**Comment by prm-dan** [comment]
@s-vkropotko - messaging directly since you seem to work on this code base the most.

**Comment by s-vkropotko** [comment]
Hi @danbosnichill @gpolek!
I've added Apache 2 license.
