### ISSUE TITLE
HA Zookeeper doesn't work with values.yaml

### ISSUE THREAD

**Issue by ckdarby** [riskfocus/helm-charts-public#7]
When running the HA set up Flink won't properly be able to connect to ZK.

This is what is ran:
```shell
helm install my-flink --namespace flink . --set \
zookeeper.enabled=true,jobmanager.replicaCount=2,jobmanager.highAvailability.enabled=true,jobmanager.highAvailability.storageDir=s3://bucket_name/flink/jobmanager
```

The issue is with the values.yaml:
`highAvailability.zookeeperConnect: zookeeper:2181`

As ZK will be installed as a dependency chart it'll also inherit the prefix of the chart name.

The ZK service won't be called `zookeeper` but instead in this example `my-flink-zookeeper`

**Comment by ckdarby** [comment]
@s-vkropotko I guess technically I could have made this into a template helper with it defaulting back to `zookeeper` if HA wasn't enabled?

Thoughts?

**Comment by vkropotko** [comment]
Hi @ckdarby!
Your solution looks reasonable. I don't think it requires additional logic.
In our tests, we override this param in values that is why it set to `zookeeper:2181`.
Thank you for contribution.
